name: youtube_search_app
description: A simple YouTube search app.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  rxdart: ^0.25.0
  provider: ^4.3.2+3
  visibility_detector: ^0.1.5
  intl: ^0.16.1
  get_it: ^5.0.3
  envify: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7
  mockito: ^4.1.3
  build_runner: ^1.10.12
  envify_generator: ^1.1.0

flutter:
  uses-material-design: true
