name: youtube_search_app
description: A simple YouTube search app.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  rxdart: ^0.25.0
  provider: ^4.3.2+3
  visibility_detector: ^0.1.5
  intl: ^0.16.1
  get_it: ^5.0.3
  envify: ^2.0.0
  json_annotation: ^3.1.1
  retrofit: ^1.3.4+1
  dio: ^3.0.10
  url_launcher: ^5.7.10
  universal_html: ^1.2.3
  freezed_annotation: ^0.12.0
  shared_preferences: ^0.5.12+4
  shared_preferences_web: ^0.1.2+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7
  mockito: ^4.1.3
  build_runner: ^1.10.12
  envify_generator: ^1.1.0
  json_serializable: ^3.5.1
  retrofit_generator: ^1.4.1
  freezed: ^0.12.6

flutter:
  uses-material-design: true
